:-initialization(consult('operators.pl')).
:-initialization(consult('api_utils.pl')).
:-initialization(consult('api_exp.pl')).
:-initialization(consult('rexp_gen.pl')).
:-initialization(consult('cexp_gen.pl')).
:-initialization(consult('bexp_gen.pl')).
:-initialization(consult('fexp_gen.pl')).
:-initialization(consult('proj_gen.pl')).
:-initialization(consult('create_hq.pl')).
:-initialization(consult('utils_derivation.pl')).
:-initialization(consult('utils.pl')).
:-initialization(consult('derivation.pl')).
:-initialization(consult('merge_function.pl')).
:-initialization(consult('config_generation.pl')).
:-initialization(consult('run_generation.pl')).
